### ISSUE TITLE
Is 50.4V(12s) the hard limit?

### ISSUE THREAD

**Issue by juodumas** [shamansystems/Cheap-FOCer-2#11]
> Up to 50.4V(12s) safe operating voltage. For 20s version take a look at these FOCers.

Can it handle above 50.4V with 20A peak?
I am using 16S LiFePo4, charging up to 56V.

**Comment by shamansystems** [comment]
The hardware is designed to handle 12S with good reliability. Anything beyond with not be as reliable and you risk damaging the FETs or DRV. 16S will almost certainly cause damage.
