### ISSUE TITLE
Link to bootloader is broken

### ISSUE THREAD

**Issue by TechnikWeber** [shamansystems/Cheap-FOCer-2#16]
Hello,
I am just ready to start but the link given un the example for flashing the bootloader is broken.

(https://electric-skateboard.builders/t/vesc-boot-loader-installation-tutorial/32103?source_topic_id=52813)

I think its a problem from Vedder Forum, but can you maybe upload it here?

**Comment by shamansystems** [comment]
get bootloader from the repo here
https://github.com/shamansystems/Cheap-FOCer-2/tree/master/firmware

I'll have to make note in the guide that the bootloader is available in the repo itself.

**Comment by TechnikWeber** [comment]
It’s working now! Thanks!
