### ISSUE TITLE
Net C17-Pad2 Connections

### ISSUE THREAD

**Issue by SRFirefox** [shamansystems/Cheap-FOCer-2#18]
Of the three vias on the C17-Pad2 net clearly intended to connect the bottom side trace to the topside trace under D6, only one via is electrically connected. 

![image](https://user-images.githubusercontent.com/10254021/86505828-66c32d80-bd97-11ea-83af-b32857f081d0.png)

**Comment by shamansystems** [comment]
Good catch! I’ll fix this for the v1.0 release.

**Comment by shamansystems** [comment]
![image](https://user-images.githubusercontent.com/49463302/86986391-31cd2700-c159-11ea-819a-29b2ae8762d9.png)

Fixed!

**Comment by SRFirefox** [comment]
Good work!
