### ISSUE TITLE
Ordering instructions differ from board-front pic shown in assembly guide

### ISSUE THREAD

**Issue by powneill** [shamansystems/Cheap-FOCer-2#19]
Assembly instructions "What your board should look like" section.  Picture shows ADC2/ADC1 section populated with resistors R72, R71, R68, and R40.  However, the BOM and CPL CSV's do not contain any reference to these components for ordering or pick-and-place.

Can you clarify whether this was an omission from CPL/BOM and these components should be added, or whether it is no longer necessary to populate those sections and the assembly guide picture is just outdated?

Thanks much

**Comment by bj97301** [comment]
Good catch. These are optional.
