### ISSUE TITLE
What is the minimal voltage for vesc control pins(gpio, uart ect.)?

### ISSUE THREAD

**Issue by astra404** [shamansystems/Cheap-FOCer-2#27]
I am planning to use stm32 ( blue pill) to control the esc. It is 3.3v only. Will it work with cheap focer?

**Comment by charclo** [comment]
The cheap focer also uses an stm32, so 3,3V is perfect

**Comment by astra404** [comment]
Good to hear. As I understand focer is also 5v compatable. But logic output is at 3.3v range. Is that correct?

**Comment by shamansystems** [comment]
The CFOC2 is capable of supplying 5V to accessories but all of the logic is 3.3V.

**Comment by astra404** [comment]
Tank you for the healp!
