### ISSUE TITLE
Cleaning the finished pcb 

### ISSUE THREAD

**Issue by astra404** [shamansystems/Cheap-FOCer-2#28]
Maby this is a dumb question but can I wash the focer by submerging it in izopropanol?
I.e there are no components that are sensitive to IPA and other solvents like bme280 is...

**Comment by astra404** [comment]
![IMG_20210401_125603.jpg](https://user-images.githubusercontent.com/61183370/113277656-a2b8fe00-92e9-11eb-9766-51c58c39f280.jpg)

**Comment by shamansystems** [comment]
You can use IPA. I use 99% ipa. Just make sure the board is dry before power up
