### ISSUE TITLE
DRV8301, TJA1051T/3/1J, SMF05CT1G are out of stock aswell as BMI160

### ISSUE THREAD

**Issue by L4stIdi0t** [shamansystems/Cheap-FOCer-2#29]
BMI160: https://github.com/shamansystems/Cheap-FOCer-2/issues/23

DRV3801 out of stock at lcsc, digikey and mouser

TJA1051T/3/1J out of stock at lcsc, digikey and mouser

SMF05CT1G out of stock at lcsc, digikey and mouser

**Comment by shamansystems** [comment]
Yeah there is a global shortage of chips in general. There's not much I can do about that.
