### ISSUE TITLE
Safe to leave out BMI160 attitude sensors?

### ISSUE THREAD

**Issue by wait-what** [shamansystems/Cheap-FOCer-2#43]
BMI160 costs €5.4547 a piece at the moment, so I was wondering if it's safe to just leave it's spot empty if I have no plans for using it?

**Comment by AntumArk** [comment]
Well if you leave out all of the required components for it as in [BMI160 datasheet](https://www.mouser.com/datasheet/2/783/BST-BMI160-DS000-1509569.pdf) and configure firmware so it would not use it, then it should be fine. The same thing is often done with MPU6050 which is also I2C device.

**Comment by wait-what** [comment]
Thank you
