### ISSUE TITLE
Schematics in PDF

### ISSUE THREAD

**Issue by Peemouse** [shamansystems/Cheap-FOCer-2#5]
Hi,

Thanks for this awesome project !
Is it possible to generate and include a PDF version of Schematics in the repo ?
Or did I miss it ?

That would ease the reading without downloading the whole project (and avoid installing Kicad).

Thanks !

Clément

**Comment by shamansystems** [comment]
Yes I can and should do this. I’m out of town but I’ll get to it once I return

**Comment by shamansystems** [comment]
Done!
