### ISSUE TITLE
bootloader

### ISSUE THREAD

**Issue by MegaC-C** [shamansystems/Cheap-FOCer-2#6]
since the url for the bootloader in the mentioned tutorial is broken, i thought it might be helpful to share a working bootloader. 

https://github.com/vedderb/vesc_tool/blob/master/res/bootloaders/60_o_75_300_o_HD_o_UAVC_OMEGA_o_75_300_R2_o_60_MK3_o_100_250_o_75_300_R3_o_60_MK4_o_60_MK5_o_HD_R2.bin

this bootloader worked fine for me:)

**Comment by shamansystems** [comment]
Bootloader is now in the repo
